/* File: curvif_simplifiedmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Thu Dec 26 20:32:27 2019
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <setjmp.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *curvif_simplified_error;
static PyObject *curvif_simplified_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define PRINTPYOBJERR(obj)\
    fprintf(stderr,"curvif_simplified.error is related to ");\
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define SWAP(a,b,t) {\
    t *c;\
    c = a;\
    a = b;\
    b = c;}

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(curvif_simplified_error,errstring);\
        /*goto capi_fail;*/\
    } else 

/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = curvif_simplified_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int create_cb_arglist(PyObject* fun,PyTupleObject* xa,const int maxnofargs,const int nofoptargs,int *nofargs,PyTupleObject **args,const char *errmess) {
    PyObject *tmp = NULL;
    PyObject *tmp_fun = NULL;
    int tot,opt,ext,siz,i,di=0;
    CFUNCSMESS("create_cb_arglist\n");
    tot=opt=ext=siz=0;
    /* Get the total number of arguments */
    if (PyFunction_Check(fun))
        tmp_fun = fun;
    else {
        di = 1;
        if (PyObject_HasAttrString(fun,"im_func")) {
            tmp_fun = PyObject_GetAttrString(fun,"im_func");
        }
        else if (PyObject_HasAttrString(fun,"__call__")) {
            tmp = PyObject_GetAttrString(fun,"__call__");
            if (PyObject_HasAttrString(tmp,"im_func"))
                tmp_fun = PyObject_GetAttrString(tmp,"im_func");
            else {
                tmp_fun = fun; /* built-in function */
                tot = maxnofargs;
                if (xa != NULL)
                    tot += PyTuple_Size((PyObject *)xa);
            }
            Py_XDECREF(tmp);
        }
        else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                tot += PyTuple_Size((PyObject *)xa);
            tmp_fun = fun;
        }
        else if (F2PyCapsule_Check(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                ext = PyTuple_Size((PyObject *)xa);
            if(ext>0) {
                fprintf(stderr,"extra arguments tuple cannot be used with CObject call-back\n");
                goto capi_fail;
            }
            tmp_fun = fun;
        }
    }
if (tmp_fun==NULL) {
fprintf(stderr,"Call-back argument must be function|instance|instance.__call__|f2py-function but got %s.\n",(fun==NULL?"NULL":Py_TYPE(fun)->tp_name));
goto capi_fail;
}
#if PY_VERSION_HEX >= 0x03000000
    if (PyObject_HasAttrString(tmp_fun,"__code__")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount"))
#else
    if (PyObject_HasAttrString(tmp_fun,"func_code")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"func_code"),"co_argcount"))
#endif
            tot = PyInt_AsLong(PyObject_GetAttrString(tmp,"co_argcount")) - di;
        Py_XDECREF(tmp);
    }
    /* Get the number of optional arguments */
#if PY_VERSION_HEX >= 0x03000000
    if (PyObject_HasAttrString(tmp_fun,"__defaults__")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
#else
    if (PyObject_HasAttrString(tmp_fun,"func_defaults")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"func_defaults")))
#endif
            opt = PyTuple_Size(tmp);
        Py_XDECREF(tmp);
    }
    /* Get the number of extra arguments */
    if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
    /* Calculate the size of call-backs argument list */
    siz = MIN(maxnofargs+ext,tot);
    *nofargs = MAX(0,siz-ext);
#ifdef DEBUGCFUNCS
    fprintf(stderr,"debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),tot,opt,ext,siz,nofargs=%d(-%d),%d,%d,%d,%d,%d\n",maxnofargs,nofoptargs,tot,opt,ext,siz,*nofargs);
#endif
    if (siz<tot-opt) {
        fprintf(stderr,"create_cb_arglist: Failed to build argument list (siz) with enough arguments (tot-opt) required by user-supplied function (siz,tot,opt=%d,%d,%d).\n",siz,tot,opt);
        goto capi_fail;
    }
    /* Initialize argument list */
    *args = (PyTupleObject *)PyTuple_New(siz);
    for (i=0;i<*nofargs;i++) {
        Py_INCREF(Py_None);
        PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
    }
    if (xa != NULL)
        for (i=(*nofargs);i<siz;i++) {
            tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
            Py_INCREF(tmp);
            PyTuple_SET_ITEM(*args,i,tmp);
        }
    CFUNCSMESS("create_cb_arglist-end\n");
    return 1;
capi_fail:
    if ((PyErr_Occurred())==NULL)
        PyErr_SetString(curvif_simplified_error,errmess);
    return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = curvif_simplified_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(curvif_simplified,CURVIF_SIMPLIFIED)(double*,void*,double*,double*,double*,int*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/***************************** curvif_simplified *****************************/
static char doc_f2py_rout_curvif_simplified_curvif_simplified[] = "\
x_opt,f_opt = curvif_simplified(x0,obj_func,lower_bounds,upper_bounds,epsilon,[n,obj_func_extra_args])\n\nWrapper for ``curvif_simplified``.\
\n\nParameters\n----------\n"
"x0 : input rank-1 array('d') with bounds (n)\n"
"obj_func : call-back function\n"
"lower_bounds : input rank-1 array('d') with bounds (n)\n"
"upper_bounds : input rank-1 array('d') with bounds (n)\n"
"epsilon : input float\n"
"\nOther Parameters\n----------------\n"
"obj_func_extra_args : input tuple, optional\n    Default: ()\n"
"n : input int, optional\n    Default: len(x0)\n"
"\nReturns\n-------\n"
"x_opt : rank-1 array('d') with bounds (n)\n"
"f_opt : float\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"#cbdocstr#";
/* extern void F_FUNC_US(curvif_simplified,CURVIF_SIMPLIFIED)(double*,void*,double*,double*,double*,int*,double*,double*); */
static PyObject *f2py_rout_curvif_simplified_curvif_simplified(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,void*,double*,double*,double*,int*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *x0 = NULL;
  npy_intp x0_Dims[1] = {-1};
  const int x0_Rank = 1;
  PyArrayObject *capi_x0_tmp = NULL;
  int capi_x0_intent = 0;
  PyObject *x0_capi = Py_None;
  PyObject *obj_func_capi = Py_None;
  PyTupleObject *obj_func_xa_capi = NULL;
  PyTupleObject *obj_func_args_capi = NULL;
  int obj_func_nofargs_capi = 0;
  obj_func_typedef obj_func_cptr;
  double *lower_bounds = NULL;
  npy_intp lower_bounds_Dims[1] = {-1};
  const int lower_bounds_Rank = 1;
  PyArrayObject *capi_lower_bounds_tmp = NULL;
  int capi_lower_bounds_intent = 0;
  PyObject *lower_bounds_capi = Py_None;
  double *upper_bounds = NULL;
  npy_intp upper_bounds_Dims[1] = {-1};
  const int upper_bounds_Rank = 1;
  PyArrayObject *capi_upper_bounds_tmp = NULL;
  int capi_upper_bounds_intent = 0;
  PyObject *upper_bounds_capi = Py_None;
  double epsilon = 0;
  PyObject *epsilon_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  double *x_opt = NULL;
  npy_intp x_opt_Dims[1] = {-1};
  const int x_opt_Rank = 1;
  PyArrayObject *capi_x_opt_tmp = NULL;
  int capi_x_opt_intent = 0;
  double f_opt = 0;
  static char *capi_kwlist[] = {"x0","obj_func","lower_bounds","upper_bounds","epsilon","n","obj_func_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|OO!:curvif_simplified.curvif_simplified",\
    capi_kwlist,&x0_capi,&obj_func_capi,&lower_bounds_capi,&upper_bounds_capi,&epsilon_capi,&n_capi,&PyTuple_Type,&obj_func_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable epsilon */
    f2py_success = double_from_pyobj(&epsilon,epsilon_capi,"curvif_simplified.curvif_simplified() 5th argument (epsilon) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x0 */
  ;
  capi_x0_intent |= F2PY_INTENT_IN;
  capi_x0_tmp = array_from_pyobj(NPY_DOUBLE,x0_Dims,x0_Rank,capi_x0_intent,x0_capi);
  if (capi_x0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(curvif_simplified_error,"failed in converting 1st argument `x0' of curvif_simplified.curvif_simplified to C/Fortran array" );
  } else {
    x0 = (double *)(PyArray_DATA(capi_x0_tmp));

  /* Processing variable f_opt */
  /* Processing variable obj_func */
if(F2PyCapsule_Check(obj_func_capi)) {
  obj_func_cptr = F2PyCapsule_AsVoidPtr(obj_func_capi);
} else {
  obj_func_cptr = obj_func;
}

  obj_func_nofargs_capi = obj_func_nofargs;
  if (create_cb_arglist(obj_func_capi,obj_func_xa_capi,#maxnofargs#,#nofoptargs#,&obj_func_nofargs,&obj_func_args_capi,"failed in processing argument list for call-back obj_func.")) {
    jmp_buf obj_func_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `obj_func`.\n");
    SWAP(obj_func_capi,obj_func_capi,PyObject);
    SWAP(obj_func_args_capi,obj_func_args_capi,PyTupleObject);
    memcpy(&obj_func_jmpbuf,&obj_func_jmpbuf,sizeof(jmp_buf));
  /* Processing variable n */
  if (n_capi == Py_None) n = len(x0); else
    f2py_success = int_from_pyobj(&n,n_capi,"curvif_simplified.curvif_simplified() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(x0)>=n,"len(x0)>=n","1st keyword n","curvif_simplified:n=%d",n) {
  /* Processing variable lower_bounds */
  lower_bounds_Dims[0]=n;
  capi_lower_bounds_intent |= F2PY_INTENT_IN;
  capi_lower_bounds_tmp = array_from_pyobj(NPY_DOUBLE,lower_bounds_Dims,lower_bounds_Rank,capi_lower_bounds_intent,lower_bounds_capi);
  if (capi_lower_bounds_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(curvif_simplified_error,"failed in converting 3rd argument `lower_bounds' of curvif_simplified.curvif_simplified to C/Fortran array" );
  } else {
    lower_bounds = (double *)(PyArray_DATA(capi_lower_bounds_tmp));

  /* Processing variable upper_bounds */
  upper_bounds_Dims[0]=n;
  capi_upper_bounds_intent |= F2PY_INTENT_IN;
  capi_upper_bounds_tmp = array_from_pyobj(NPY_DOUBLE,upper_bounds_Dims,upper_bounds_Rank,capi_upper_bounds_intent,upper_bounds_capi);
  if (capi_upper_bounds_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(curvif_simplified_error,"failed in converting 4th argument `upper_bounds' of curvif_simplified.curvif_simplified to C/Fortran array" );
  } else {
    upper_bounds = (double *)(PyArray_DATA(capi_upper_bounds_tmp));

  /* Processing variable x_opt */
  x_opt_Dims[0]=n;
  capi_x_opt_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_x_opt_tmp = array_from_pyobj(NPY_DOUBLE,x_opt_Dims,x_opt_Rank,capi_x_opt_intent,Py_None);
  if (capi_x_opt_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(curvif_simplified_error,"failed in converting hidden `x_opt' of curvif_simplified.curvif_simplified to C/Fortran array" );
  } else {
    x_opt = (double *)(PyArray_DATA(capi_x_opt_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(obj_func_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(x0,obj_func_cptr,lower_bounds,upper_bounds,&epsilon,&n,x_opt,&f_opt);
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("Nd",capi_x_opt_tmp,f_opt);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_x_opt_tmp == NULL) ... else of x_opt*/
  /* End of cleaning variable x_opt */
  if((PyObject *)capi_upper_bounds_tmp!=upper_bounds_capi) {
    Py_XDECREF(capi_upper_bounds_tmp); }
  }  /*if (capi_upper_bounds_tmp == NULL) ... else of upper_bounds*/
  /* End of cleaning variable upper_bounds */
  if((PyObject *)capi_lower_bounds_tmp!=lower_bounds_capi) {
    Py_XDECREF(capi_lower_bounds_tmp); }
  }  /*if (capi_lower_bounds_tmp == NULL) ... else of lower_bounds*/
  /* End of cleaning variable lower_bounds */
  } /*CHECKSCALAR(len(x0)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
    CFUNCSMESS("Restoring jmpbuf for `obj_func`.\n");
    obj_func_capi = obj_func_capi;
    Py_DECREF(obj_func_args_capi);
    obj_func_args_capi = obj_func_args_capi;
    obj_func_nofargs = obj_func_nofargs_capi;
    memcpy(&obj_func_jmpbuf,&obj_func_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable obj_func */
  /* End of cleaning variable f_opt */
  if((PyObject *)capi_x0_tmp!=x0_capi) {
    Py_XDECREF(capi_x0_tmp); }
  }  /*if (capi_x0_tmp == NULL) ... else of x0*/
  /* End of cleaning variable x0 */
  } /*if (f2py_success) of epsilon*/
  /* End of cleaning variable epsilon */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of curvif_simplified **************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"curvif_simplified",-1,{{-1}},0,(char *)F_FUNC_US(curvif_simplified,CURVIF_SIMPLIFIED),(f2py_init_func)f2py_rout_curvif_simplified_curvif_simplified,doc_f2py_rout_curvif_simplified_curvif_simplified},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "curvif_simplified",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_curvif_simplified(void) {
#else
#define RETVAL
PyMODINIT_FUNC initcurvif_simplified(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = curvif_simplified_module = PyModule_Create(&moduledef);
#else
  m = curvif_simplified_module = Py_InitModule("curvif_simplified", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module curvif_simplified (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'curvif_simplified' is auto-generated with f2py (version:2).\nFunctions:\n"
"  x_opt,f_opt = curvif_simplified(x0,obj_func,lower_bounds,upper_bounds,epsilon,n=len(x0),obj_func_extra_args=())\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  curvif_simplified_error = PyErr_NewException ("curvif_simplified.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"curvif_simplified");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
